---
  environment: development
  #chdir: 
  address: 127.0.0.1
  #user: gd
  #group: gd
  port: 4568
  pid: thin.pid
  rackup: config.ru
  log: thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: true
